dist: trusty
sudo: required

language: python

python:
    - "2.7"

services:
    - docker

before_install:
    - pip install jupyter-repo2docker

# test building container only
script: repo2docker . --no-run
